In [5]:
import numpy as np

In [6]:
data = np.array([1,2,3,4])

In [7]:
data = np.array(range(10))

In [8]:
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
data.argmin()

0

In [10]:
data.argmax()

9

In [11]:
np.random.random()

0.5937909148428084

In [12]:
data=np.random.randint(low=10, high=100,size=10)

In [13]:
data

array([29, 10, 69, 44, 71, 84, 50, 63, 88, 62])

In [14]:
data.argmax()

8

In [15]:
data.argmin()

1

In [16]:
np.max(data)

88

In [17]:
np.min(data)

10

In [18]:
x1=np.random.randint(50,size=10)

In [19]:
x1

array([ 9, 30, 44, 24, 42,  9, 45, 34, 14, 47])

In [20]:
x2 = np.random.randint(15, size=(3,6))

In [21]:
x2

array([[ 0, 13,  9,  8,  6, 13],
       [ 8, 13,  6,  8,  6,  8],
       [14, 14,  4,  5, 11,  9]])

In [22]:
x2.ndim

2

In [23]:
x2.size

18

In [24]:
x2.shape

(3, 6)

In [25]:
x2.dtype

dtype('int64')

In [26]:
np.array(['hello','Worl1d'])

array(['hello', 'Worl1d'], 
      dtype='|S6')

In [27]:
x2[1,2]

6

In [28]:
x2

array([[ 0, 13,  9,  8,  6, 13],
       [ 8, 13,  6,  8,  6,  8],
       [14, 14,  4,  5, 11,  9]])

In [29]:
x2[2,5] = 700

In [30]:
x2

array([[  0,  13,   9,   8,   6,  13],
       [  8,  13,   6,   8,   6,   8],
       [ 14,  14,   4,   5,  11, 700]])

In [31]:
x1


array([ 9, 30, 44, 24, 42,  9, 45, 34, 14, 47])

In [32]:
x1[2:8:2]

array([44, 42, 45])

In [33]:
x1[:5]

array([ 9, 30, 44, 24, 42])

In [34]:
x1[5:]

array([ 9, 45, 34, 14, 47])

In [35]:
x1[4:8]

array([42,  9, 45, 34])

In [36]:
x2

array([[  0,  13,   9,   8,   6,  13],
       [  8,  13,   6,   8,   6,   8],
       [ 14,  14,   4,   5,  11, 700]])

In [37]:
x2[1,2:4]

array([6, 8])

In [41]:
import numpy as np

In [42]:
%%timeit
a=np.arange(10000)
np.sum(a)

The slowest run took 4.36 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 21.1 µs per loop


In [40]:
%timeit np.sum(a)

NameError: global name 'a' is not defined

In [ ]:
a