In [1]:
import numpy as np

In [64]:
a = np.array([[[[[[[[2],[3],[3],[4],[5],[6],[8],[0]]]]]]]])

In [69]:
a

array([[[[[[[[2],
             [3],
             [3],
             [4],
             [5],
             [6],
             [8],
             [0]]]]]]]])

In [70]:
x=np.array(range(10))

In [71]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
y=x

In [73]:
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
y[2]=2

In [83]:
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
z=x.copy()

In [90]:
z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
z[0]=33

In [93]:
z

array([33,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [94]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
x.reshape((1,10))

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [118]:
x=np.array([1,2,3,5,6])
y=np.array([4,5,6])

In [111]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [112]:
x+y

array([5, 7, 9])

In [113]:
x-y

array([-3, -3, -3])

In [114]:
x/y

array([0, 0, 0])

In [115]:
x*y

array([ 4, 10, 18])

In [116]:
np.sum(x)

6

In [119]:
x

array([1, 2, 3, 5, 6])

In [120]:
np.sum(x)

17

In [121]:
sum(range(5999))

17991001

In [140]:
x=np.arange(10)

In [141]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [160]:
a4,a5=np.hsplit(x,2)

In [162]:
a4

array([0, 1, 2, 3, 4])

In [164]:
a5

array([5, 6, 7, 8, 9])

In [176]:
x=np.random.randint(10,size=(4,6))

In [177]:
x

array([[4, 4, 5, 0, 4, 9],
       [6, 4, 7, 7, 1, 5],
       [7, 4, 5, 3, 3, 0],
       [6, 4, 8, 5, 6, 0]])

In [196]:
o,t=np.hsplit(x,2)

In [197]:
q,p = np.vsplit(x,2)

In [198]:
p

array([[7, 4, 5, 3, 3, 0],
       [6, 4, 8, 5, 6, 0]])

In [199]:
q

array([[4, 4, 5, 0, 4, 9],
       [6, 4, 7, 7, 1, 5]])

In [200]:
u,v=np.vsplit(t,2)

In [201]:
t


array([[0, 4, 9],
       [7, 1, 5],
       [3, 3, 0],
       [5, 6, 0]])

In [202]:
o

array([[4, 4, 5],
       [6, 4, 7],
       [7, 4, 5],
       [6, 4, 8]])

In [205]:
np.hstack([t,o])

array([[0, 4, 9, 4, 4, 5],
       [7, 1, 5, 6, 4, 7],
       [3, 3, 0, 7, 4, 5],
       [5, 6, 0, 6, 4, 8]])

In [208]:
np.vstack([o,t])

array([[4, 4, 5],
       [6, 4, 7],
       [7, 4, 5],
       [6, 4, 8],
       [0, 4, 9],
       [7, 1, 5],
       [3, 3, 0],
       [5, 6, 0]])

In [209]:
np.concatenate([o,t])

array([[4, 4, 5],
       [6, 4, 7],
       [7, 4, 5],
       [6, 4, 8],
       [0, 4, 9],
       [7, 1, 5],
       [3, 3, 0],
       [5, 6, 0]])

In [210]:
np.concatenate([t,o])

array([[0, 4, 9],
       [7, 1, 5],
       [3, 3, 0],
       [5, 6, 0],
       [4, 4, 5],
       [6, 4, 7],
       [7, 4, 5],
       [6, 4, 8]])

In [214]:
x=np.arange(8)

In [215]:
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [216]:
x1,x2,x3 = np.split(x,[3,5])

In [217]:
x1

array([0, 1, 2])

In [218]:
x2

array([3, 4])

In [219]:
x3

array([5, 6, 7])

In [220]:
x = np.random.randint(10,size=(4,6))

In [221]:
x

array([[0, 3, 4, 7, 1, 0],
       [6, 8, 6, 4, 2, 4],
       [2, 8, 1, 4, 3, 9],
       [4, 9, 5, 2, 1, 2]])

In [225]:
np.hsplit(x,[3,6])

[array([[0, 3, 4],
        [6, 8, 6],
        [2, 8, 1],
        [4, 9, 5]]), array([[7, 1, 0],
        [4, 2, 4],
        [4, 3, 9],
        [2, 1, 2]]), array([], shape=(4, 0), dtype=int64)]

In [2]:
import numpy as np
a=np.arange(10)

In [3]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.add.reduce(a)

45

In [5]:
np.sum(a)

45

In [6]:
np.add.accumulate(a)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [8]:
np.argmax(a)

9

In [11]:
a = np.random.randint(8,size=(5,5))

In [12]:
a

array([[2, 6, 2, 1, 2],
       [5, 7, 3, 2, 6],
       [7, 1, 4, 0, 1],
       [4, 6, 7, 0, 2],
       [7, 1, 3, 2, 3]])

In [14]:
np.max(a,
       axis=1)

array([6, 7, 7, 7, 7])

In [15]:
np.max(a,axis=0)

array([7, 7, 7, 2, 6])

In [16]:
np.mean(a)

3.3599999999999999

In [17]:
np.mean(a,axis=1)

array([ 2.6,  4.6,  2.6,  3.8,  3.2])

In [18]:
np.mean(a,axis=0)

array([ 5. ,  4.2,  3.8,  1. ,  2.8])

In [19]:
np.std(a)

2.3130931671681538

In [20]:
np.std(a,axis=0)

array([ 1.8973666 ,  2.63818119,  1.72046505,  0.89442719,  1.72046505])

In [21]:
np.std(a,axis=1)

array([ 1.74355958,  1.8547237 ,  2.57681975,  2.56124969,  2.03960781])

### Pandas


In [1]:
import numpy as np
import pandas as pd

In [5]:
ab = pd.Series(['Student A','Student B','Student C','Student D'], index=[1,2,3,4])

In [9]:
cd = pd.Series(['Josephs','Christ','JnC','UM','SU'], index=[1,2,3,4,5])

In [10]:
ab

1    Student A
2    Student B
3    Student C
4    Student D
dtype: object

In [11]:
cd

1    Josephs
2     Christ
3        JnC
4         UM
5         SU
dtype: object

In [18]:
ef = pd.Series(['89','45','75','88','78'], index = [1,2,3,4,5])

In [19]:
ef

1    89
2    45
3    75
4    88
5    78
dtype: object

In [20]:
gh = pd.DataFrame({'ab':ab, 'cd':cd, 'ef':ef})

In [21]:
gh

ab       cd  ef
1  Student A  Josephs  89
2  Student B   Christ  45
3  Student C      JnC  75
4  Student D       UM  88
5        NaN       SU  78

In [27]:
student = pd.Series(['Tom', 'Dic','Harry','Anabelle'])

In [34]:
subjects = pd.Series(['Maths', 'Science','Chemistry','Sociology'])

In [47]:
marks = pd.Series([78,65,35,34])

In [48]:
student

0         Tom
1         Dic
2       Harry
3    Anabelle
dtype: object

In [49]:
Report = pd.DataFrame({'student':student, 'subjects':subjects, 'marks':marks})

In [50]:
Report

marks   student   subjects
0     78       Tom      Maths
1     65       Dic    Science
2     35     Harry  Chemistry
3     34  Anabelle  Sociology

In [53]:
Report[Report['marks'] >40]

marks student subjects
0     78     Tom    Maths
1     65     Dic  Science